apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-todo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-todo-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: default
     name: django-todo-pvc
  hostPath:
    type: DirectoryOrCreate
    path: "/data"
---
